export const examples = {
  'alert-dialog': () => import('./alert-dialog').then((m) => m.examples),
  alert: () => import('./alert').then((m) => m.examples),
  avatar: () => import('./avatar').then((m) => m.examples),
  badge: () => import('./badge').then((m) => m.examples),
  button: () => import('./button').then((m) => m.examples),
  card: () => import('./card').then((m) => m.examples),
  checkbox: () => import('./checkbox').then((m) => m.examples),
  chip: () => import('./chip').then((m) => m.examples),
  combobox: () => import('./combobox').then((m) => m.examples),
  dialog: () => import('./dialog').then((m) => m.examples),
  divider: () => import('./divider').then((m) => m.examples),
  dropdown: () => import('./dropdown').then((m) => m.examples),
  field: () => import('./field').then((m) => m.examples),
  fieldset: () => import('./fieldset').then((m) => m.examples),
  heading: () => import('./heading').then((m) => m.examples),
  'icon-box': () => import('./icon-box').then((m) => m.examples),
  'input-group': () => import('./input-group').then((m) => m.examples),
  input: () => import('./input').then((m) => m.examples),
  item: () => import('./item').then((m) => m.examples),
  kbd: () => import('./kbd').then((m) => m.examples),
  label: () => import('./label').then((m) => m.examples),
  pagination: () => import('./pagination').then((m) => m.examples),
  popover: () => import('./popover').then((m) => m.examples),
  progress: () => import('./progress').then((m) => m.examples),
  radio: () => import('./radio').then((m) => m.examples),
  select: () => import('./select').then((m) => m.examples),
  separator: () => import('./separator').then((m) => m.examples),
  sidebar: () => import('./sidebar').then((m) => m.examples),
  slider: () => import('./slider').then((m) => m.examples),
  spinner: () => import('./spinner').then((m) => m.examples),
  stack: () => import('./stack').then((m) => m.examples),
  switch: () => import('./switch').then((m) => m.examples),
  table: () => import('./table').then((m) => m.examples),
  tabs: () => import('./tabs').then((m) => m.examples),
  text: () => import('./text').then((m) => m.examples),
  textarea: () => import('./textarea').then((m) => m.examples),
  toast: () => import('./toast').then((m) => m.examples),
  tooltip: () => import('./tooltip').then((m) => m.examples),
};

export type ExampleName = keyof typeof examples;

export const exampleNames = Object.keys(examples) as ExampleName[];
